services:
  web:
    build: ./ExpenseTrackerProject
    links:
      - postgres:postgres
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ExpenseTrackerProject/:/usr/src/ExpenseTrackerProject/
    ports:
      - "8000:8000"
    env_file:
      - .envs/.django
      - .envs/.postgres

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.postgres

volumes:
  pg_data:
