# Generated by Django 5.0.6 on 2024-07-15 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('GROCERIES', 'Groceries'), ('LEISURE', 'Leisure'), ('ELECTRONICS', 'Electronics'), ('UTILITIES', 'Utilities'), ('CLOTHING', 'Clothing'), ('HEALTH', 'Health'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('expense_creator', models.ForeignKey(db_column='expense_creator', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
